const quotes = [
  // Money & wealth
  ["The successful warrior is the average man, with laser-like focus.", "Bruce Lee"],
  ["Wealth consists not in having great possessions, but in having few wants.", "Epictetus"],
  ["Someone's sitting in the shade today because someone planted a tree long ago.", "Warren Buffett"],
  ["The stock market is a device for transferring money from the impatient to the patient.", "Warren Buffett"],
  ["Do not save what is left after spending, spend what is left after saving.", "Warren Buffett"],
  ["Rich people believe 'I create my life.' Poor people believe 'Life happens to me.'", "T. Harv Eker"],
  ["An investment in knowledge pays the best interest.", "Benjamin Franklin"],
  ["It's not how much money you make, but how much money you keep.", "Robert Kiyosaki"],
  ["Never depend on a single income.", "Warren Buffett"],
  ["The habit of saving is itself an education.", "T.T. Munger"],
  ["Rich people have small TVs and big libraries; poor people have small libraries and big TVs.", "Zig Ziglar"],
  ["You must gain control over your money or the lack of it will forever control you.", "Dave Ramsey"],
  ["Financial freedom is available to those who learn about it and work for it.", "Robert Kiyosaki"],
  ["The individual investor should act consistently as an investor and not as a speculator.", "Benjamin Graham"],
  ["Not saving money is like a farmer not tilling the soil.", "Jim Rohn"],
  ["Money is a terrible master but an excellent servant.", "P.T. Barnum"],
  ["Price is what you pay. Value is what you get.", "Warren Buffett"],
  ["Risk comes from not knowing what you're doing.", "Warren Buffett"],
  ["Rule No. 1: Never lose money. Rule No. 2: Never forget rule No. 1.", "Warren Buffett"],
  ["Compound interest is the eighth wonder of the world.", "Albert Einstein"],
  ["The four most dangerous words in investing are: 'this time it's different.'", "Sir John Templeton"],
  ["In investing, what is comfortable is rarely profitable.", "Robert Arnott"],
  ["The real measure of your wealth is how much you'd be worth if you lost all your money.", "Unknown"],
  ["A budget is telling your money where to go instead of wondering where it went.", "Dave Ramsey"],
  ["Money often costs too much.", "Ralph Waldo Emerson"],
  ["Formal education will make you a living; self-education will make you a fortune.", "Jim Rohn"],
  ["Beware of little expenses; a small leak will sink a great ship.", "Benjamin Franklin"],
  ["A penny saved is a penny earned.", "Benjamin Franklin"],
  ["Money looks better in the bank than on your feet.", "Sophia Amoruso"],
  ["If you want to be wealthy, you can't think and talk like everyone else.", "Steve Siebold"],
  ["Every time you borrow money, you're robbing your future self.", "Nathan W. Morris"],
  ["The more you learn, the more you earn.", "Warren Buffett"],
  ["Cash combined with courage in a time of crisis is priceless.", "Warren Buffett"],
  ["Never spend your money before you have earned it.", "Thomas Jefferson"],
  ["Save a little money each month and at the end of the year you'll be surprised how little you have.", "Ernest Haskins"],
  ["Frugality includes all the other virtues.", "Cicero"],
  ["Too many people spend money they haven't earned, to buy things they don't want, to impress people they don't like.", "Will Rogers"],
  ["The goal isn't more money. The goal is living life on your terms.", "Chris Brogan"],
  ["Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.", "Ayn Rand"],
  ["Diversification is protection against ignorance.", "Warren Buffett"],
  ["It takes 20 years to build a reputation and five minutes to ruin it.", "Warren Buffett"],
  ["Don't tell me where your priorities are. Show me where you spend your money and I'll tell you what they are.", "James W. Frick"],
  ["A man who both spends and saves money is the happiest man, because he has both enjoyments.", "Samuel Johnson"],
  ["It's not your salary that makes you rich, it's your spending habits.", "Charles A. Jaffe"],
  ["The individual who wants to reach the top in business must appreciate the might of the totality of little things.", "John D. Rockefeller"],
  ["It is remarkable how much long-term advantage people like us have gotten by trying to be consistently not stupid, instead of trying to be very intelligent.", "Charlie Munger"],
  ["Spend each day trying to be a little wiser than you were when you woke up.", "Charlie Munger"],
  ["The big money is not in the buying and selling, but in the waiting.", "Charlie Munger"],
  ["Knowing what you don't know is more useful than being brilliant.", "Charlie Munger"],
  ["Buy assets while you're young, they buy you freedom when you're older.", "Unknown"],
  ["Every dollar you save at 25 is worth ten dollars you save at 55.", "Unknown"],
  ["Seek wealth, not money or status. Wealth is having assets that earn while you sleep.", "Naval Ravikant"],
  ["Play long-term games with long-term people.", "Naval Ravikant"],
  ["The best investment you can make is in your own abilities.", "Warren Buffett"],

  // Career, hustle & ambition
  ["Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.", "Steve Jobs"],
  ["The way to get started is to quit talking and begin doing.", "Walt Disney"],
  ["Don't watch the clock; do what it does. Keep going.", "Sam Levenson"],
  ["Opportunities don't happen. You create them.", "Chris Grosser"],
  ["I find that the harder I work, the more luck I seem to have.", "Thomas Jefferson"],
  ["There are no traffic jams along the extra mile.", "Roger Staubach"],
  ["Success usually comes to those who are too busy to be looking for it.", "Henry David Thoreau"],
  ["Don't be afraid to give up the good to go for the great.", "John D. Rockefeller"],
  ["I never dreamed about success, I worked for it.", "Estée Lauder"],
  ["Efforts and courage are not enough without purpose and direction.", "John F. Kennedy"],
  ["Whatever the mind can conceive and believe, it can achieve.", "Napoleon Hill"],
  ["It is during our darkest moments that we must focus to see the light.", "Aristotle"],
  ["The only limit to our realization of tomorrow is our doubts of today.", "Franklin D. Roosevelt"],
  ["You miss 100% of the shots you don't take.", "Wayne Gretzky"],
  ["The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt"],
  ["It always seems impossible until it's done.", "Nelson Mandela"],
  ["Do what you can with all you have, wherever you are.", "Theodore Roosevelt"],
  ["The only way to do great work is to love what you do.", "Steve Jobs"],
  ["Ideas are easy. Implementation is hard.", "Guy Kawasaki"],
  ["If you are not embarrassed by the first version of your product, you've launched too late.", "Reid Hoffman"],
  ["Your most unhappy customers are your greatest source of learning.", "Bill Gates"],
  ["I have not failed. I've just found 10,000 ways that won't work.", "Thomas Edison"],
  ["Genius is 1% inspiration and 99% perspiration.", "Thomas Edison"],
  ["If you really look closely, most overnight successes took a long time.", "Steve Jobs"],
  ["Chase the vision, not the money; the money will end up following you.", "Tony Hsieh"],
  ["Build something 100 people love, not something 1 million people kind of like.", "Brian Chesky"],
  ["The best way to predict the future is to create it.", "Peter Drucker"],
  ["Stay hungry, stay foolish.", "Steve Jobs"],
  ["Work like there is someone working 24 hours a day to take it away from you.", "Mark Cuban"],
  ["Sweat equity is the most valuable equity there is.", "Mark Cuban"],
  ["It's not about ideas. It's about making ideas happen.", "Scott Belsky"],
  ["Discipline is the bridge between goals and accomplishment.", "Jim Rohn"],
  ["Hard work beats talent when talent doesn't work hard.", "Tim Notke"],
  ["Focus on being productive instead of busy.", "Tim Ferriss"],
  ["You don't have to be great to start, but you have to start to be great.", "Zig Ziglar"],
  ["A goal without a plan is just a wish.", "Antoine de Saint-Exupéry"],
  ["Well done is better than well said.", "Benjamin Franklin"],
  ["There's no shortage of remarkable ideas, what's missing is the will to execute them.", "Seth Godin"],
  ["Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", "Stephen King"],
  ["Vision without execution is hallucination.", "Thomas Edison"],
  ["Action is the foundational key to all success.", "Pablo Picasso"],
  ["The distance between your dreams and reality is called action.", "Unknown"],
  ["You are never too old to set another goal or to dream a new dream.", "C.S. Lewis"],
  ["What we fear of doing most is usually what we most need to do.", "Ralph Waldo Emerson"],
  ["The man who moves a mountain begins by carrying away small stones.", "Confucius"],
  ["It does not matter how slowly you go as long as you do not stop.", "Confucius"],
  ["Success is not final, failure is not fatal: it is the courage to continue that counts.", "Winston Churchill"],
  ["Quality means doing it right when no one is looking.", "Henry Ford"],
  ["The only place where success comes before work is in the dictionary.", "Vidal Sassoon"],
  ["There are no shortcuts to any place worth going.", "Beverly Sills"],
  ["Don't count the days, make the days count.", "Muhammad Ali"],
  ["Champions keep playing until they get it right.", "Billie Jean King"],
  ["You have to expect things of yourself before you can do them.", "Michael Jordan"],
  ["Excellence is not a skill, it's an attitude.", "Ralph Marston"],
  ["The road to success and the road to failure are almost exactly the same.", "Colin R. Davis"],
  ["If you're not willing to risk the usual, you will have to settle for the ordinary.", "Jim Rohn"],
  ["The price of success is hard work, dedication to the job at hand.", "Vince Lombardi"],
  ["Follow effective action with quiet reflection. From the quiet reflection will come even more effective action.", "Peter Drucker"],
  ["Efficiency is doing things right; effectiveness is doing the right things.", "Peter Drucker"],
  ["What gets measured gets managed.", "Peter Drucker"],
  ["There is no elevator to success, you have to take the stairs.", "Unknown"],
  ["Little by little, a little becomes a lot.", "Tanzanian Proverb"],
  ["The expert in anything was once a beginner.", "Helen Hayes"],
  ["Don't limit your challenges, challenge your limits.", "Unknown"],

  // Resilience & failure
  ["It's not whether you get knocked down, it's whether you get up.", "Vince Lombardi"],
  ["Fall seven times, stand up eight.", "Japanese Proverb"],
  ["Success is stumbling from failure to failure with no loss of enthusiasm.", "Winston Churchill"],
  ["The comeback is always stronger than the setback.", "Unknown"],
  ["Our greatest glory is not in never falling, but in rising every time we fall.", "Confucius"],
  ["What doesn't kill you makes you stronger.", "Friedrich Nietzsche"],
  ["Failure is simply the opportunity to begin again, this time more intelligently.", "Henry Ford"],
  ["I've failed over and over and over again in my life and that is why I succeed.", "Michael Jordan"],
  ["You just can't beat the person who never gives up.", "Babe Ruth"],
  ["Turn your wounds into wisdom.", "Oprah Winfrey"],
  ["The oak fought the wind and was broken, the willow bent when it must and survived.", "Robert Jordan"],
  ["Rock bottom became the solid foundation on which I rebuilt my life.", "J.K. Rowling"],
  ["Difficulties in life are intended to make us better, not bitter.", "Dan Reeves"],
  ["When you have exhausted all possibilities, remember this: you haven't.", "Thomas Edison"],
  ["The greatest glory in living lies not in never falling, but in rising every time we fall.", "Nelson Mandela"],
  ["Adversity causes some men to break, others to break records.", "William A. Ward"],
  ["Storms make trees take deeper roots.", "Dolly Parton"],
  ["Tough times never last, but tough people do.", "Robert H. Schuller"],
  ["Resilience is knowing that you are the only one that has the power and responsibility to pick yourself up.", "Mary Holloway"],
  ["The bamboo that bends is stronger than the oak that resists.", "Japanese Proverb"],
  ["You may have to fight a battle more than once to win it.", "Margaret Thatcher"],
  ["Perseverance is not a long race; it is many short races one after the other.", "Walter Elliot"],
  ["Every adversity carries with it the seed of an equivalent or greater benefit.", "Napoleon Hill"],
  ["The struggle you're in today is developing the strength you need for tomorrow.", "Robert Tew"],
  ["Character consists of what you do on the third and fourth tries.", "James A. Michener"],
  ["A smooth sea never made a skilled sailor.", "Franklin D. Roosevelt"],
  ["When the going gets tough, the tough get going.", "Joseph P. Kennedy"],
  ["It's not the load that breaks you down, it's the way you carry it.", "Lou Holtz"],
  ["Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, 'I will try again tomorrow.'", "Mary Anne Radmacher"],
  ["Pain is temporary. Quitting lasts forever.", "Lance Armstrong"],
  ["Grit is falling down seven times and getting up eight.", "Unknown"],
  ["The strongest people are not those who show strength in front of us, but those who win battles we know nothing about.", "Unknown"],
  ["In the middle of difficulty lies opportunity.", "Albert Einstein"],
  ["Great things never came from comfort zones.", "Unknown"],
  ["Do not judge me by my success, judge me by how many times I fell down and got back up again.", "Nelson Mandela"],
  ["You never know how strong you are until being strong is your only choice.", "Bob Marley"],
  ["He who has a why to live can bear almost any how.", "Friedrich Nietzsche"],
  ["Persistence guarantees that results are inevitable.", "Paramahansa Yogananda"],
  ["Winners are not people who never fail, but people who never quit.", "Unknown"],

  // Youth, time & your 20s / 30s
  ["The best time to plant a tree was 20 years ago. The second best time is now.", "Chinese Proverb"],
  ["In your 20s you build the skills; in your 30s you build the wealth; in your 40s you build the legacy.", "Unknown"],
  ["Your twenties are the perfect time to fail forward — you have nothing to lose and everything to learn.", "Unknown"],
  ["The two most important days in your life are the day you are born and the day you find out why.", "Mark Twain"],
  ["Youth is not a time of life; it is a state of mind.", "Samuel Ullman"],
  ["The days are long, but the decades are short.", "Sam Altman"],
  ["Time is the most valuable thing a man can spend.", "Theophrastus"],
  ["Don't wait. The time will never be just right.", "Napoleon Hill"],
  ["The trouble is, you think you have time.", "Buddha"],
  ["By the time you're 30, discipline should have already replaced motivation.", "Unknown"],
  ["What you do in your 20s and 30s determines the options you have in your 50s and 60s.", "Unknown"],
  ["Compound interest applies to skills, relationships, and reputation — not just money. Start early.", "Unknown"],
  ["The person who starts simply with the intention to start, but with no intention to finish, will never finish.", "Bruce Lee"],
  ["Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did.", "Mark Twain"],
  ["Your time is limited, so don't waste it living someone else's life.", "Steve Jobs"],
  ["You don't need more time, you just need to decide.", "Seth Godin"],
  ["Someday is not a day of the week.", "Denise Brennan-Nelson"],
  ["In 20 years you'll wish you had started today.", "Unknown"],
  ["The earlier you start compounding — money, skills, relationships — the more unfair the advantage becomes.", "Naval Ravikant"],
  ["Your 20s are not a dress rehearsal. They are the opening act.", "Unknown"],
  ["Most people overestimate what they can do in a year, and underestimate what they can do in a decade.", "Bill Gates"],
  ["The best investment you can make is in yourself, especially in your 20s and 30s.", "Warren Buffett"],
  ["By 25 you should know your craft; by 30 you should be dangerous at it.", "Unknown"],
  ["The advantage of youth is you can take risks nobody with a mortgage can.", "Unknown"],
  ["Your network in your 20s becomes your net worth in your 40s.", "Unknown"],
  ["Skills compound faster than money — build them in your 20s and cash out for the rest of your life.", "Unknown"],
  ["Nobody cares how hard you worked in your 20s until you're the only one still standing in your 40s.", "Unknown"],
  ["The 30-year-olds who look like overnight successes were unknown and grinding at 22.", "Unknown"],
  ["Every year you delay starting is a year of compounding you never get back.", "Unknown"],
  ["Youth ends when egotism does; maturity begins when one lives for others.", "Hermann Hesse"],
  ["Take the risk or lose the chance.", "Unknown"],
  ["Now is the worst time to start; and also the best. Start now.", "Unknown"],
  ["We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "Aristotle"],
  ["The man who has confidence in himself gains the confidence of others.", "Hasidic Proverb"],
  ["Setting goals is the first step in turning the invisible into the visible.", "Tony Robbins"],
  ["The only person you are destined to become is the person you decide to be.", "Ralph Waldo Emerson"],
  ["Don't judge each day by the harvest you reap but by the seeds that you plant.", "Robert Louis Stevenson"],
  ["Success is walking from failure to failure with no loss of enthusiasm.", "Winston Churchill"],
  ["The harder the conflict, the more glorious the triumph.", "Thomas Paine"],
  ["Obstacles are those frightful things you see when you take your eyes off your goal.", "Henry Ford"],
  ["It's not the mountain we conquer but ourselves.", "Sir Edmund Hillary"],
  ["Believe you can and you're halfway there.", "Theodore Roosevelt"],
  ["Nothing in the world can take the place of persistence.", "Calvin Coolidge"],
  ["The only impossible journey is the one you never begin.", "Tony Robbins"],
  ["Motivation is what gets you started. Habit is what keeps you going.", "Jim Ryun"],
  ["Small daily improvements over time lead to stunning results.", "Robin Sharma"],
  ["What you get by achieving your goals is not as important as what you become by achieving your goals.", "Zig Ziglar"],
  ["You are the average of the five people you spend the most time with.", "Jim Rohn"],
  ["Your income is determined by your habits of thought.", "Napoleon Hill"],
  ["The man who has no money is poor, but a man who has nothing but money is poorer still.", "Unknown"],
  ["Build your empire in your 20s; enjoy it in your 30s; multiply it in your 40s.", "Unknown"],
  ["The best revenge for a rough childhood is a rich adulthood.", "Unknown"],
];

const params = new URLSearchParams(location.search);
document.getElementById("site").textContent = params.get("site") || "this site";

if (params.get("reason") === "adult") {
  document.querySelector(".sub").textContent =
    "This category is permanently blocked and can't be changed from settings.";
}

const [quote, author] = quotes[Math.floor(Math.random() * quotes.length)];
document.getElementById("quote").textContent = `"${quote}"`;
document.getElementById("author").textContent = `— ${author}`;

document.getElementById("back").addEventListener("click", () => {
  if (history.length > 1) {
    history.back();
  } else {
    chrome.tabs.getCurrent((tab) => {
      if (tab) chrome.tabs.remove(tab.id);
    });
  }
});
